name: Check and Restart payHook Space

on:
  schedule:
    - cron: '*/30 * * * *'  # 每30分钟检查一次,一个月2*24*30=1440<2000(普通账户限制)
  workflow_dispatch:  # 允许手动触发
jobs:
  check-space-status:
    runs-on: ubuntu-latest
    env:
      SPACE_NAME: "rogerxavier/payHook"
      TOKEN: "${{ secrets.HF_SPACE_API_TOKEN }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check Space Status
        id: check_status
        run: |
          response=$(curl -s -H "Authorization: Bearer $TOKEN" "https://huggingface.co/api/spaces/$SPACE_NAME")
          stage=$(echo "$response" | jq -r '.runtime.stage')
          echo "Space stage: $stage"
          echo "::set-output name=stage::$stage"
      - name: Check Space Status and restart
        if: steps.check_status.outputs.stage != 'RUNNING'
        run: |
          echo "Restarting the space..."
          curl -X POST -H "Authorization: Bearer $TOKEN" "https://huggingface.co/api/spaces/$SPACE_NAME/restart"
